const express = require('express');
const router = express.Router();
const { getAllReports, updateReportStatus, syncExternalData, getStats } = require('../controllers/adminController');
const { protect, adminOnly } = require('../middleware/auth');
router.use(protect, adminOnly);
router.get('/disasters', getAllReports);
router.put('/disasters/:id/status', updateReportStatus);
router.post('/sync-disasters', syncExternalData);
router.get('/stats', getStats);
module.exports = router;
